include: [index.html, CppCoreGuidelines.md]
exclude: [guidelines, docs, talks, Gemfile, params.json]

defaults:
  - scope:
      path: "fr"
    values:
      layout: default

collections:
  fr:
    sort_by: path
    output: true
    permalink: /fr/:name
