include: [index.html, CppCoreGuidelines.md]
exclude: [guidelines, docs, talks, Gemfile, params.json]
collections:
  fr:
    sort_by: path
    output: true
    permalink: /fr/:name
    layout: default
